#!/usr/bin/env bash
# Full rebuild of the Ghidra IL2CPP reference. Run once after a game update (the binary changes).
# Heavy: Il2CppDumper, a full Ghidra auto-analysis pass, signature/type application, and a full
# decompile of every type (an hour or more in total). Produces decompiled/ghidra/ and refreshes the
# saved project so tools/re/decompile.sh queries are fast.
#
#   tools/re/refresh.sh                                # uses the default Steam install path
#   tools/re/refresh.sh "/c/path/to/Disco Elysium"     # or an explicit game folder
#   tools/re/refresh.sh "" 3                           # resume at stage 3 (earlier stages' output kept)
#
# Locations (tool folder, JDK) come from tools/re/env.sh. Do not edit this file while it runs: bash
# reads a script incrementally, so a shifted file derails the running instance.
set -euo pipefail

GAME="${1:-}"; GAME="${GAME:-${DISCO_ELYSIUM_DIR:-/c/Program Files (x86)/Steam/steamapps/common/Disco Elysium}}"
FROM="${2:-1}"
DLL="$GAME/GameAssembly.dll"
META="$GAME/disco_Data/il2cpp_data/Metadata/global-metadata.dat"
[ -f "$DLL" ] || { echo "GameAssembly.dll not found at: $DLL" >&2; exit 1; }
[ -f "$META" ] || { echo "global-metadata.dat not found at: $META" >&2; exit 1; }

source "$(dirname "${BASH_SOURCE[0]}")/env.sh"
[ -f "$DUMPER" ] || { echo "Il2CppDumper not found at $DUMPER; see tools/re/README.md (setup)." >&2; exit 1; }
[ -f "$HEADER_TO_GHIDRA" ] || { echo "il2cpp_header_to_ghidra.py not found at $HEADER_TO_GHIDRA; see tools/re/README.md (setup)." >&2; exit 1; }

cd "$RE_HOME"
mkdir -p in out/dumper project "$REPO/decompiled/ghidra"

if [ "$FROM" -le 1 ]; then
  echo "[1/5] Il2CppDumper (symbol map, structs) ..."
  cp "$DLL" in/GameAssembly.dll
  rm -f out/dumper/script.json
  # Il2CppDumper ends with a "press any key" ReadKey: with stdin from /dev/null it throws instead of
  # blocking forever, and the dump is already complete by then, so ignore the failure.
  "$DUMPER" "$DLL" "$META" out/dumper < /dev/null || true
  [ -f out/dumper/script.json ] || { echo "Il2CppDumper did not produce script.json" >&2; exit 1; }
  ( cd out/dumper && python "$HEADER_TO_GHIDRA" )   # il2cpp.h -> il2cpp_ghidra.h
fi

if [ "$FROM" -le 2 ]; then
  echo "[2/5] Ghidra import + auto-analysis + method names (the long one) ..."
  headless "$PROJECT_WIN" GameAssembly -overwrite \
    -import "$RE_HOME_WIN\\in\\GameAssembly.dll" -scriptPath "$SCRIPTS_WIN" \
    -postScript ApplyIl2Cpp.java "$DUMPER_OUT_WIN\\script.json"
fi

if [ "$FROM" -le 3 ]; then
  echo "[3/5] type + signature application (named struct fields) ..."
  headless "$PROJECT_WIN" GameAssembly -process GameAssembly.dll -noanalysis \
    -scriptPath "$SCRIPTS_WIN" \
    -postScript ApplyStructs.java "$DUMPER_OUT_WIN\\script.json" "$DUMPER_OUT_WIN\\il2cpp_ghidra.h"
fi

if [ "$FROM" -le 4 ]; then
  echo "[4/5] global string legend ..."
  python - "$RE_HOME/out/dumper/script.json" "$REPO/decompiled/ghidra/_strings.txt" <<'PY'
import io, json, sys
d = json.load(open(sys.argv[1], encoding='utf-8'))
with io.open(sys.argv[2], 'w', encoding='utf-8') as o:
    for i, s in enumerate(d.get('ScriptString', []), 1):
        o.write(u'StringLiteral_%d\t%s\n' % (i, (s.get('Value') or '').replace('\r','').replace('\n','\\n')))
PY
fi

echo "[5/5] full per-type decompile -> decompiled/ghidra/ ..."
headless "$PROJECT_WIN" GameAssembly -process GameAssembly.dll -noanalysis \
  -scriptPath "$SCRIPTS_WIN" -postScript FullExport.java "$GHIDRA_OUT_WIN"

echo "done. Reference rebuilt in decompiled/ghidra/; query a class with tools/re/decompile.sh <Type\$\$>."
